### PR TITLE
package: updated webpack support up to 1.8.x

### PR DESCRIPTION
**Pull request by Zolmeister**

### CODE REVIEW

**Comment by Zolmeister** [comment]
On another note, have you considered using the `^` syntax for this dependency?
They seem to stick to semver

**Comment by shama** [comment]
Thanks! I prefer explicit deps because authors tend to stick to semver until they don't. Also if the meaning of `^` ever changes in npm again, it won't affect my explicit deps.

**Comment by Zolmeister** [comment]
I figured that this is `gulp-webpack`, and at least the main webpack dependency should stay up-to-date

**Comment by Zolmeister** [comment]
If you wouldn't mind publishing the update soon it would be greatly appreciated.

**Comment by shama** [comment]
Published as `1.4.0`.

**Pull request merged**
